# Generated by Django 4.0.4 on 2022-05-03 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default='manager', max_length=50)),
                ('asset_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Request',
            new_name='EmployeeRequest',
        ),
        migrations.DeleteModel(
            name='Asset',
        ),
    ]
