# Generated by Django 4.0.4 on 2022-04-27 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Asset',
            new_name='CompanyAsset',
        ),
    ]
