# Generated by Django 4.0.4 on 2022-04-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(max_length=50)),
                ('request_type', models.CharField(max_length=50)),
                ('urgenty', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Request',
        ),
    ]
