# Generated by Django 4.0.4 on 2022-04-26 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_employeerequest_delete_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeerequest',
            old_name='urgenty',
            new_name='urgency',
        ),
    ]
