# Generated by Django 4.0.4 on 2022-04-26 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('werden_auth', '0002_managerprofile_employeeprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managerprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='EmployeeProfile',
        ),
        migrations.DeleteModel(
            name='ManagerProfile',
        ),
    ]
