# Generated by Django 4.0.4 on 2022-05-02 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('werden_auth', '0005_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
